CREATE TABLE CUSTOMER (
    CustomerID INT NOT NULL PRIMARY KEY,
    Name CHAR(20) NOT NULL,
    Surname CHAR(20) NOT NULL ,
    Email CHAR(40) NOT NULL,
);

CREATE TABLE PURCHASE (
    PurchaseID INT NOT NULL PRIMARY KEY,
    FormOfPurchase CHAR(13) NOT NULL ,
    Payment CHAR(5) NOT NULL,
	DateOfPurchase Date NOT NULL,
);

CREATE TABLE EMPLOYEE (
    EmployeeID INT NOT NULL PRIMARY KEY,
    Name CHAR(20) NOT NULL,
    Surname CHAR(20) NOT NULL ,
    Position CHAR(20) NOT NULL,
);

CREATE TABLE SEWINGROOM (
    SewingRoomID INT NOT NULL PRIMARY KEY,
    Adress CHAR(20) NOT NULL,
    Specialization CHAR(20) NOT NULL ,
);

CREATE TABLE SHOP (
    ShopID INT NOT NULL PRIMARY KEY,
);

CREATE TABLE SUPPLIED_BY (
    FK_ShopID INT NOT NULL FOREIGN KEY REFERENCES SHOP(ShopID) ON DELETE CASCADE,
	FK_SewingRoomID INT NOT NULL FOREIGN KEY REFERENCES SEWINGROOM(SewingRoomID) ON DELETE CASCADE,
);

CREATE TABLE EMPLOYMENT (
    EmploymentID INT NOT NULL PRIMARY KEY,
    FK_ShopID INT NOT NULL FOREIGN KEY REFERENCES SHOP(ShopID) ON DELETE CASCADE,
	FK_EmployeeID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE,
);

CREATE TABLE ITEM (
    ItemID INT NOT NULL PRIMARY KEY,
    Size CHAR(2) NOT NULL,
    Material CHAR(20) NOT NULL ,
    Price CHAR(20) NOT NULL,
    Gender CHAR(20) NOT NULL,
    Colour CHAR(9) NOT NULL,
    Model CHAR(20) NOT NULL,
    NumberOfAvaiableProducts INT NOT NULL,
	FK_ShopID INT NOT NULL FOREIGN KEY REFERENCES SHOP(ShopID) ON DELETE CASCADE, 
);

CREATE TABLE HISTORY (
    HistoryID INT NOT NULL PRIMARY KEY,
    FK_PurchaseID INT NOT NULL FOREIGN KEY REFERENCES PURCHASE(PurchaseID) ON DELETE CASCADE,
	FK_CustomerID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE,
	FK_ItemID INT NOT NULL FOREIGN KEY REFERENCES ITEM(ItemID) ON DELETE CASCADE,
);

CREATE TABLE RETURNS (
    ReturnID INT NOT NULL PRIMARY KEY,
    AfterHowManyDays INT NOT NULL,
	WasAccepted CHAR(3) NOT NULL,
    Reason CHAR(20) NOT NULL ,
    DateOfReturn DATE NOT NULL,
    DayOfTheWeek CHAR(20) NOT NULL,
	FK_HistoryID INT NOT NULL FOREIGN KEY REFERENCES HISTORY(HistoryID) ON DELETE CASCADE,
);


SELECT * FROM SHOP;
SELECT * FROM SEWINGROOM;
SELECT * FROM ITEM;
SELECT * FROM RETURNS;
SELECT * FROM EMPLOYEE;
SELECT * FROM CUSTOMER;
SELECT * FROM PURCHASE;
SELECT * FROM EMPLOYMENT;
SELECT * FROM HISTORY;
SELECT * FROM SUPPLIED_BY;

SELECT COUNT(*) FROM SHOP;
SELECT COUNT(*) FROM SEWINGROOM;
SELECT COUNT(*) FROM ITEM;
SELECT COUNT(*) FROM RETURNS;
SELECT COUNT(*) FROM EMPLOYEE;
SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM PURCHASE;
SELECT COUNT(*) FROM EMPLOYMENT;
SELECT COUNT(*) FROM HISTORY;
SELECT COUNT(*) FROM SUPPLIED_BY;

DROP TABLE RETURNS;
DROP TABLE HISTORY;
DROP TABLE ITEM;
DROP TABLE EMPLOYMENT;
DROP TABLE SUPPLIED_BY;
DROP TABLE SHOP;
DROP TABLE SEWINGROOM;
DROP TABLE EMPLOYEE;
DROP TABLE PURCHASE;
DROP TABLE CUSTOMER;

ALTER TABLE SHOP
ADD StartDate date; 
ALTER TABLE SHOP
ADD FinishDate date; 
SELECT  MIN(DateOfReturn) FROM RETURNS


SELECT * FROM PURCHASE
